import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Index from "./pages/Index";
import Houses from "./pages/Houses";
import About from "./pages/About";
import Characters from "./pages/Characters";
import NotFound from "./pages/NotFound";
import MovingModal from "./pages/Modal";
import Memes from "./pages/Memes";

const queryClient = new QueryClient();

const App = () => (
  <QueryClientProvider client={queryClient}>
    <TooltipProvider>
      <Toaster />
      <Sonner />
      <BrowserRouter>
      < MovingModal/>
        <Routes>
          <Route path="/" element={<Index />} />
          <Route path="/houses" element={<Houses />} />
          <Route path="/characters" element={<Characters />} />
          <Route path="/about" element={<About />} />
          <Route path="/memes" element={<Memes />} />
          <Route path="*" element={<NotFound />} />
        </Routes>
      </BrowserRouter>
    </TooltipProvider>
  </QueryClientProvider>
);

export default App;



/*

       Моя любовь к nFactorial :                                      
                                                  
        :~!?JJJJ?7~:          :~7?JJJJ?!~:        
     .~JPPPPPPPPPPPPY7:    :7YPPPPPPPPPPPPJ~.     
    ^YPPPPPPPPPPPPPPPPP?..?PPPPPPPPPPPPPPPPPY^    
   ~PPPPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPPPPPPPPP~   
  .5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.  
  ^PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP^  
  ^PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP^  
  .5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.  
   ?PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP?   
   .5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5.   
    :YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY:    
     .7PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP7.     
       :?PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP?:       
         :75PPPPPPPPPPPPPPPPPPPPPPPPPP57:         
           .!YPPPPPPPPPPPPPPPPPPPPPPY!.           
              ^?PPPPPPPPPPPPPPPPPP?^              
                :75PPPPPPPPPPPP57:                
                  .~JPPPPPPPPJ~.                  
                     ^?PPPP?^                     
                       :77:                       
                                               
*/
/*  
@@@@@@&GPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG&@@@@@@
@@@@@&PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJ~^:^!5PPPPPPPPPPPPPPPP&@@@@@
@@@@#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJ      ^PPPPPPPPPPPPPPPPP#@@@@
@@@&PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP7      .5PPPPPPPPPPPPPPPPP&@@@
@@&PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP?      .5PPPPPPPPPPPPPPPPPP&@@
@@GPPPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPPPP555PPPPPPPP55Y55PPPPPPPPPPPPPPJ      :PPPPPPPPPPPPPPPPPPPG@@
@#PPPPPPPPPPPPPPPPPPPPP7:   :?PPPPPPPPY^    ^YPPJ!^:.....:^7YPPPPPPPPPPY      ~PPPPPPPPPPPPPPPPPPPP#@
@GPPPPPPPPPPPPPPPPPPPPJ       YPPPPPPP~                     ~5PPPPPPPP5.     7PPPPPPPPPPPPPPPPPPPPG@
#PPPPPPPPPPPPPPPPPPPPP5~     ~5PPPPPPP^        .^!777~.      :5PPPPPPPP:     JPPPPPPPPPPPPPPPPPPPPP#
BPPPPPPPPPPPPPPPPPPPPPPPY?7?YPPPPPPPPP^       !5PPPPPPY:      ?PPPPPPPP^     YPPPPPPPPPPPPPPPPPPPPPB
GPPPPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPP^      !PPPPPPPPP7      !PPPPPPPP!    .5PPPPPPPPPPPPPPPPPPPPPG
PPPPPPPPPPPPPPPPPPPPPPPP5?!75PPPPPPPPP^      YPPPPPPPPPJ      !PPPPPPPP?    ^PPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPP~   ^PPPPPPPPP^      YPPPPPPPPPJ      !PPPPPPPP5:   JPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPP5.    YPPPPPPPP^     .YPPPPPPPPPJ      !PPPPPPPPP5??YPPPPPPPPPPPPPPPPPPPPPPPP
GPPPPPPPPPPPPPPPPPPPPPPY     ?PPPPPPPP^      YPPPPPPPPPJ      !PPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPPPPG
BPPPPPPPPPPPPPPPPPPPPPP?     7PPPPPPPP^      YPPPPPPPPPJ      !PPPPPPPP5?!~!JPPPPPPPPPPPPPPPPPPPPPPB
#PPPPPPPPPPPPPPPPPPPPPP!     ~PPPPPPPP^      YPPPPPPPPPJ      !PPPPPPPJ.     ~PPPPPPPPPPPPPPPPPPPPP#
@GPPPPPPPPPPPPPPPPPPPPP^     ^PPPPPPPP!     .5PPPPPPPPPY      ?PPPPPPP?      .5PPPPPPPPPPPPPPPPPPPG@
@#PPPPPPPPPPPPPPPPPPPP5.     :5PPPPPPP5!:.:~YPPPPPPPPPPPJ^:.:7PPPPPPPPP?^:::!YPPPPPPPPPPPPPPPPPPPP#@
@@GPPPPPPPPPPPPPPPPPPPY      .5PPPPPPPPPP5PPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG@@
@@&PPPPPPPPPPPPPPPPPPPJ       YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP&@@
@@@&PPPPPPPPPPPPPPPPPPJ       JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP&@@@
@@@@#PPPPPPPPPPPPPPPPP5:     :5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#@@@@
@@@@@&PPPPPPPPPPPPPPPPP57~~~?5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP&@@@@@
@@@@@@&GPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG&@@@@@@

*/
